### ISSUE TITLE
RAD v2 files appear to use OPL2 instead of OPL3

### ISSUE THREAD

**Issue by prochazkaml** [yoyofr/modizer#102]
Old RAD v1 files work great (except the OPL2 emulation, which is a bit off, but nobody has ever made a perfect emulator for that chip, so I can't really complain), but upon loading the newer RAD v2 files, everything sounds a bit off.

Given that the RAD v2 format has significant differences in the file structure to accommodate more features, I assume that the player used in modizer supports the new format (including "riffs", which did not exist in RAD v1), however, half of the channels are missing and some instruments, when they do play, sound way off. Which makes sense, since the RAD v2 format targets the OPL3 sound chip, which supports more waveforms and has double the channels compared to the older and less capable OPL2, which RAD v1 used.

**Comment by yoyofr** [comment]
will update to latest adplug and propose Nuked OPL (OPL3) by default in the settings, should solve this issue

**Comment by yoyofr** [comment]
Adplug has been update, issue fixed in dev build, will be part of v3.6.

**Comment by yoyofr** [comment]
v3.6 released
