### ISSUE TITLE
DS playback issues and TXTP functionality bizzare

### ISSUE THREAD

**Issue by Tetronimo777** [yoyofr/modizer#104]
DS games ripped in 2SF seems very stuttery and janky (noticeable with songs that have a fast and steady beat)(the latter half of Drawcia Sourceress from canvas curse is an example). NCSF is improved but carries over that formats own limits (missing instruments for some songs)

TXTP doesnt look in local directories nor does it seem to initiate subsongs. Link is attached to download files for testing [Download](https://drive.google.com/file/d/1lz35upSSHfksNTfkeItriVaK1teS-9g3/view?usp=sharing)

**Comment by yoyofr** [comment]
2SF files are requiring more ressources/CPU, so stuttering can happen if CPU isn't fast enough.
TXTP implementation wasn't very good in the old vgmstream modizer is relying on in v3.2.
In next version, I have updated to latest one and it sounds correct (i.e. it initializes the right subsongs).
