### ISSUE TITLE
Add option in app to change the sf2 soundfont

### ISSUE THREAD

**Issue by QcSamuel** [yoyofr/modizer#107]
title

**Comment by yoyofr** [comment]
V3.6 will automatically use a different sf2 file if present in the same folder as the midi file.
It will look 1st for a sf2 file sharing same name (ex: for music.mid file, it will look for music.sf2) and if not found it will take the sf2 file found in same directory.

**Comment by QcSamuel** [comment]
> V3.6 will automatically use a different sf2 file if present in the same folder as the midi file. It will look 1st for a sf2 file sharing same name (ex: for music.mid file, it will look for music.sf2) and if not found it will take the sf2 file found in same directory.

ok thanks will close this issue when its out

**Comment by QcSamuel** [comment]
thanks
