### ISSUE TITLE
MOD format crashes visualization

### ISSUE THREAD

**Issue by pe1rrr** [yoyofr/modizer#110]
Hello, the mod format appears to be the only format the crashes the app when tapping the screen to load the viz while a .mod is playing, the app crashes.

On an iPad Pro here, but also occurs on a iPhone 13. Makes screening modules a bit difficult not being able to see the pattern data :-)

m0d/modarchive

**Comment by pe1rrr** [comment]
Hi,

I have already tried resetting the app, and i don't want to uninstall it again- however I have recorded you a video of how it is used and it producing the bug on the iPad.

https://youtu.be/gY3QB9uJjX4

I hope this is more informative!

Good luck,
-m0d

**Comment by yoyofr** [comment]
Fixed in v3. 3
