### ISSUE TITLE
Attempting to play SSF file results in crash

### ISSUE THREAD

**Issue by TheGuyinShades** [yoyofr/modizer#111]
Whenever I play an SSF file modizer immediately crashes. I'm not sure what plugin handles them, but they were working prior to the recent update.

**Comment by yoyofr** [comment]
thanks for the report. I've checked, that's a bug related to adding the new sndh player.
Both are using starscream M68k emulator and linker is getting lost in function calls.
I've just fixed it in current dev version.
Will publish a v3.4 quickly
