### ISSUE TITLE
PSF files won't play unless renamed to PSF2

### ISSUE THREAD

**Issue by TheGuyinShades** [yoyofr/modizer#112]
This is a minor issue, but PSF files can't be played unless the extension is changed to PSF2. This happens even if they come from a PS1 game and originally had the PSF extension.

This issue wasn't introduced with the new version, it has been the case since I've using it (about a year).

**Comment by yoyofr** [comment]
Are you sure it's not the files you use which are having issues ?
I've just tried and both psf & minipsf files play ok in my dev build (no change on PSF compared / v3.3).
Please try download a file from JoshW or Modland (if modland, download first the psflib before any minipsf file).
-> online tab / choose JoshW/Console/PS1 or choose Modland / Format 'Playstation Sound Format'

**Comment by TheGuyinShades** [comment]
All my PSF files are from JoshW, I downloaded a soundtrack from Modland to compare and the results were the same. 

The files will play if they have a minipsf or psf2 extension, but if it has a psf extension modizer will hang for a few seconds and then come back, but the file won't play.

**Comment by yoyofr** [comment]
that's very strange. I tried again with v3.3 from appstore and it works (tried xenogear from joshw).
Please share a file that isn't working for you.
Did you also try to reset your settings ?
You have v3.3 installed ? Would be useful to have your device details (device model, iOS version)

**Comment by TheGuyinShades** [comment]
Resetting my settings did fix it, thank you! I thought I had tried that already, I'm sorry. Thank you for your work on this and the SSF problem!
