### ISSUE TITLE
NSFPlug does not respect infinite playback mode

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#113]
While subtracks do *sort of* respect it, the music fades away at 2:30 and stays silent throughout.

**Comment by yoyofr** [comment]
fixed in v3.5

**Comment by yoyofr** [comment]
Could you please share some files  so that I can test/reproduce the issue?

**Comment by 0x5066** [comment]
I've tested this with "super mario bros 1, 2, vs extra tracks (fds).nsf" from MODLAND (though this affects practically any NSF file).
First track always appears with a duration of 2:35, subtracks are then "infinite".

This isn't ideal as there are tracks that exceed the 2:35 length, so them restarting in the middle, or in the case of the Super Mario Bros. NSF, hearing it fade out and suddenly restart from the beginning catch someone off-guard, especially since they'd expect it to play infinitely long with no interruptions.

There is a song by Persune called "Fell", due to Internet issues I can't provide a link to it at this moment, but it is a song that exceeds 2:35 and thus never finishes playing to completion.

**Comment by yoyofr** [comment]
OK thanks will check

Le lun. 26 févr. 2024 à 12:52, Eris Lund ***@***.***> a
écrit :

**Comment by 0x5066** [comment]
[fell.zip](https://github.com/yoyofr/modizer/files/14407218/fell.zip)
Here's the NSF file I mentioned

**Comment by yoyofr** [comment]
Thanks. I have changed the infinite loop behaviour for NSFPlay: it will remove the fadeout allowing gapless looping.
Also I will add a specific default length settings in plugins/nsfplay to let you choose default length when not defined in the file itself

**Comment by yoyofr** [comment]
v3.6 released

**Comment by 0x5066** [comment]
I think providing a Default Length slider is a perfect middle ground (even if I'd prefer it to be longer, like 40 minutes or something, some people are weird like that :) ) for solving the issue, thanks!

**Comment by yoyofr** [comment]
I've improved the slider component, in v3.7 it will allow to select a wider range of default playtime duration
