### ISSUE TITLE
CLOCK setting no longer respected (as well as missing other options)

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#114]
With the change to WebSID, the CLOCK setting is now no longer respected, as well as options like filter settings and SID addresses are missing, though there's probably a reason why they're missing.

**Comment by yoyofr** [comment]
Yes, the new playback Lib has less option. I had negative feedback on the
sound quality and accuracy so I'll work on having previous Lib available
and ideally possibility to switch between both until I can have better
oscilloscope support in sidplayfp.

Le mar. 20 févr. 2024 à 14:56, Eris Lund ***@***.***> a
écrit :

**Comment by yoyofr** [comment]
fixed in v3.5, libsidplayfp brought back (latest version, 2.6)
