### ISSUE TITLE
Potential Volume Issue with NSFPlay

### ISSUE THREAD

**Issue by vincent404** [yoyofr/modizer#115]
I’m not sure which is more accurate to the volume, but on some Famicom games (Gimmick as an example) the volume on the added sound chips sounds louder on GME vs NSFPlay. Is it possible this is a bug or just a quirk on how NSFPlay does its emulation on those chips?

**Comment by yoyofr** [comment]
Not a bug, two different emulation library can have different output.
NSFPlay is often considered as more accurate, but for old nfs files some options have to be turned on, in particular for mapper N163.
Also GME might have more post processing which can explain some volume differences.
