### ISSUE TITLE
Skip to next song function no longer working from lock screen and Bluetooth

### ISSUE THREAD

**Issue by digistorm79** [yoyofr/modizer#117]
Since a couple of versions, I can no longer skip to the next song from the Lock Screen of via Bluetooth. Skipping to the previous song still works with these methods. I already ruled out all other options because everything is up to date, rebooted and it still works in all other music players.

**Comment by yoyofr** [comment]
That s a bug that will fixed in next version.


Le lun. 4 mars 2024 à 14:56, Remko Brugman ***@***.***> a
écrit :

**Comment by yoyofr** [comment]
Meanwhile it might work by keeping the button pressed for 1 or 2seconds.

Le lun. 4 mars 2024 à 14:56, Remko Brugman ***@***.***> a
écrit :
