### ISSUE TITLE
Support of FLAC audio files

### ISSUE THREAD

**Issue by tmagri** [yoyofr/modizer#119]
Since native iOS does not support FLAC. Is there a possibility that modizer can have the ability to play FLAC files.
FLAC is outside the scope of chip tune playing, so consider this a nice to have.
Thanks for a great player!

**Comment by yoyofr** [comment]
Have you tried a FLAC file ? It should already be supported 😄

**Comment by tmagri** [comment]
Hi Yoyofr/Modizer,

Yes, seems the player halts, until I pick a file that is a different
format. So I thought possibly unsupported. Tried different flac files all
halt when attempt to play.

I am running iOS 17.4.


Thanks!

**Comment by yoyofr** [comment]
It seems to work ok in my current dev build (v3.6 beta).
Could you please share a file not working in v3.5 so that I can confirm it will work in v3.6?

**Comment by tmagri** [comment]
A sample file, 
https://drive.google.com/file/d/1JPTngGxH22awcGYs5SGJL_Q5AxZ0B7fH/view?usp=sharing

as per YouTube video provided link https://youtu.be/xymTUHtRO3U?si=W48e3KDHUxBnPt6l

All Flac files regardless seem to not play on my iPhone 15,

Thanks

**Comment by jaystermusic** [comment]
Chiming in here. I believe FLAC is supported by VGMStream and it may use FFmpeg to decode, so this may be a similar issue to what happened to opus files. FLAC doesn’t seem to work in 3.5 for me either.

**Comment by yoyofr** [comment]
Yes, that’s the same issue. It works fine in my dev build, so will ok in v3.6

**Comment by yoyofr** [comment]
v3.6 released
