### ISSUE TITLE
Output midi files after opening the piano keyboard

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#121]
I was shocked by the powerful piano keyboard display function of v3.6. In addition to vgm, it also supports many formats such as sndh and sid. Thank you for your work.
On the other hand, I would like to make an additional request. Now that the piano keyboard has been output, is it possible to output midi files while playing music? This is very helpful for studying music. I know this is almost beyond just one player.

**Comment by yoyofr** [comment]
thanks for the feedback. To output true midi data should be managed through a dedicated application as it involves a lot more complexity (not the job of a player).
