### ISSUE TITLE
3.6 feedback

### ISSUE THREAD

**Issue by Abster876** [yoyofr/modizer#122]
The new release is great!  Just one thing I forgot to mention.  The driver for the 2sf playback might need updating.  It doesn't want to play Castlevania Dawn of Sorrow or Portrait of Ruin.  It DOES play Order of Ecclesia just fine.  I'm unsure if it's the .2sf that needs updating or the plugin.

**Comment by yoyofr** [comment]
thanks. Have you tried to change the default player (xsf VS vio2sf) ? Vio2sf is an older version which sometimes works better.
Also could you please attached the files you have issues with ? I've done a quick check using both JoshW and Modland and I was able to play some mini2sf files for Castlevania Dawn of Sorow & Portrait of Ruin on my dev build which should be the same a v3.6

**Comment by yoyofr** [comment]
the "now playing" playlist shortcut is broken on v3.6 (can be accessed from main player screen by tapping the 3 horizontal lines in top right-hand corner). It is fixed in dev build, I will release a 3.7 quickly.

**Comment by Abster876** [comment]
Oh, I didn’t see that option at first.  The 2sfs for both Dawn and Portrait play properly when I switch to vio2sf.  That being said they only default to a 2:30 playtime and doesn’t seem to truly support endless play mode.

**Comment by yoyofr** [comment]
I need to check / endless play mode as I'm not vio2sf & xsf support it natively. Also will maybe require to reset the file as it is often not manage in the original music.
Regarding the 2:30 default playtime I think it should be ok if you use the JoshW version (online tab, then JoshW/Portable/NDS) which comes with better tagged 2sf files and/or m3u playlist data.

**Comment by Abster876** [comment]
From my testing it seems like XSF works fine with endless play mode but vio2sf does not.  Some other plugins may have lost native endless mode playback but I’ll have to experiment to see which ones they might be.

**Comment by yoyofr** [comment]
Should be fixed with 3.7 that is now released
