### ISSUE TITLE
Playlists adding more instances of GBS tracks when sorting

### ISSUE THREAD

**Issue by jaystermusic** [yoyofr/modizer#124]
Hello,

I’ve noticed a bug in version 3.6 that adds duplicate instances of GBS tracks in your playlist when you sort the playlist. For instance, I had this track from Zoop in my playlist once, but after sorting the playlist, it was added several times. Also seems to happen any time you simply play the playlist. Not sure if this happens with other formats, I’ve only tested with GBS.

![IMG_2694](https://github.com/yoyofr/modizer/assets/86585949/9500828e-e1f7-401d-84af-a8c396cdd73f)

**Comment by yoyofr** [comment]
Hi, I tried to reproduce the issue but without success.
Also it seems something is wrong as this entry seems to be the 2nd subsong (from the name) but the path shows it should be the 1st one (the '?0' at the end). Could you try to clean the DB (maintenance/clean the database)?
Alternatively could please share more details about the steps to reproduce, including attaching the file?

**Comment by jaystermusic** [comment]
It's really odd; it doesn't seem to happen with every file. Try adding the individual tracks on the m3u in this zip to a new playlist. On my end, once you add the tracks and go back to the playlist, they show up twice. Then after sorting the playlist and exiting re-opening the playlist, the amount of tracks doubles again.

[J.League Fighting Soccer - The King of Ace Strikers.zip](https://github.com/yoyofr/modizer/files/15265198/J.League.Fighting.Soccer.-.The.King.of.Ace.Strikers.zip)

**Comment by yoyofr** [comment]
hi, I've just tried and have no issue. I suspect a corrupted database. Did you update to latest version (3.7) and have you done a database cleanup ?

**Comment by jaystermusic** [comment]
Tried updating and did a DB cleanup, but still wasn’t working. I reset the database and everything seems to work now. Thanks for looking into it.

**Comment by jaystermusic** [comment]
Worked after resetting database.

**Comment by yoyofr** [comment]
Good news, thanks for the update.
