### ISSUE TITLE
Including libgsf in an iOS App

### ISSUE THREAD

**Issue by mhaseebkhan** [yoyofr/modizer#24]
First things first, I am not reporting an issue here. :)

I am working on an iOS app in which I am required to read MSG files and display them within my app. Quick search on the Internet suggested that using libgsf can have it done for me, however, I am unable to find any valid pointers as how I can include libgsf in my app and then how I can use it to read files.

Do you have some sort of a how-to or some sample code which can help me with that?

Please let me know at the earliest convenience as I am on a very tight deadline.

Thanks in advance.

**Comment by jonnermut** [comment]
@mhaseebkhan did you get anything working for displaying MSG files in iOS?

**Comment by kirans** [comment]
@mhaseebkhan did you get anything working for iOS?
