### ISSUE TITLE
About VGM(play) Version

### ISSUE THREAD

**Issue by vus7294** [yoyofr/modizer#26]
i saw vgm core version in modizer is 1.70 and VGMplay verson is 0.40.5.
Well. there is a new version came out 2015. that version is 1.71(VGM), 0.40.7(VGMplay).
vgm 1.71 and vgmplay 0.40.7 have more chiptune compatibility feature c352, nmk112(okim6295)(later toaplan 2), Wonderswan, NES, And more.
i think you say "Compile yourself guy." But i don't have ios development technology and I DON'T HAVE MAC.
hmm.. what's your opinion, developer?

**Comment by NexusEast** [comment]
wait a sec, if you don't have any Mac, then who's selling modizer on AppStore??

**Comment by NexusEast** [comment]
Just wait for author update VGM & VGMPlay to latest, then wait for him (or she? I doubt it. ) upload modizer to AppStore.
