### ISSUE TITLE
NSF doesn't respect global default length

### ISSUE THREAD

**Issue by Sappharad** [yoyofr/modizer#29]
Any NSF file that doesn't internally specify a length defaults to libGME's built in default of 2:30 instead of the value you pick in settings.

This generally only impacts homebrew NSF's, such as most entries to the Famicompo contests. Haven't checked to see if you have control over this, but figured I'd report it so that it's documented somewhere.

**Comment by yoyofr** [comment]
Thanks for reporting,  it's a known bug fixed in upcoming v2.6.
