### ISSUE TITLE
Distorted sound output from PMDMini(May be frequency related)

### ISSUE THREAD

**Issue by internetakias** [yoyofr/modizer#30]
PMD tracks sound distorted, and said distortion sounds very similar to hoot's when the frequency isn't set to the one the PC98's sound cards natively output at, 55.5khz(55,466.66666666667 to be exact but either 55466 or 55467 work for hoot). Hope you can look into this. Thanks.

**Comment by yoyofr** [comment]
not a bug, rather an feature request. No plan for now
