### ISSUE TITLE
any plan to support these extensions?

### ISSUE THREAD

**Issue by vus7294** [yoyofr/modizer#32]
I always thanks for you support new vgm and streamed vgms. and I hope some update for these extension support.

.at3 (Playstation Portable, Playstaion 3 VGM)
.at9 (Playstation Vita, Playstation 4 VGM)
.xma, .xwma (XBOX 360 Generic VGM)
.wsr (Wonderswan VGM)

wsr has own plugin. at9 uses newest version of VGMStream.

additional problem - if I turn on Endless Loop, VGMs use VGMStream don't play normally. only solution is turn off that.

Edit
Good news. at9 Finally playable in VGMSTREAM. at3, at9, xma are using newest vgmstream.

**Comment by vus7294** [comment]
i can't edit the thread oh come on...

Edit by reply
I Found again AT3 and XMA use just VGMSTREAM. but at3 and xma on droidsound-e use FFMPEG. hmm...

**Comment by ArtemisZakhary** [comment]
Could I add my suggestion?

Could you somehow update VGMStream library for support of  this extension

.tak (Tom's lossless Audio Kompressor)

.tak uses newest version of VGMStream

**Comment by yoyofr** [comment]
partial support (dependant of underlying codec) in v2.9.4
to be extended in next versions with more codecs supported
