### ISSUE TITLE
HVSC content missing

### ISSUE THREAD

**Issue by cliffordcarnmo** [yoyofr/modizer#33]
I just did a fresh install of Modizer v2.9 from the App Store on my iPhone 8 Plus and opened the application. I then tried to search for "salmon" to get to /MUSICIANS/B/Blues_Muz/Gallefoss_Glenn/Curved_Salmon.sid. However the search returns zero results (yes, "HVSC" was selected in the list of search providers). I then browsed the HVSC collection in the app to /MUSICIANS/B/Blues_Muz/Gallefoss_Glenn/ but the song Curved_Salmon.sid is not there.

Is this because Modizer and HVSC is not in sync? I read at https://itunes.apple.com/us/app/modizer/id393964792?mt=8 that "HVSC updated to #68 and mirrors updated" but I still can't find the same content on Modizer and HVSC #68.

Can I somehow force a mirror refresh in the app or am I doing something completely wrong?

Thanks!

**Comment by cliffordcarnmo** [comment]
Thanks buddy! We are touring northern scandinavia this summer going to a bunch of demoparties and we use to have Modizer running the music through Bluetooth in the car :-)

**Comment by yoyofr** [comment]
ok, it reminds me some good memories (I was part of a small french
demogroup in the late 90's).
v2.9.1 just submitted to appstore, should be reviewed & hopefully validated
soon. It includes a proper DB update for HVSC #68.

rgds,
ym

Le ven. 15 juin 2018 à 09:29, Clifford Carnmo <notifications@github.com> a
écrit :

**Comment by cliffordcarnmo** [comment]
I just updated Modizer and #67 works now. Thank you very(!) much for your fast response and resolve. Our trip is saved 😀
