### ISSUE TITLE
Please support Apple CarPlay.

### ISSUE THREAD

**Issue by alexmyczko** [yoyofr/modizer#34]
is that hard to add?

**Comment by yoyofr** [comment]
I will need to check, have never looked at it so far

Le ven. 17 mai 2019 à 08:56, Alex Myczko <notifications@github.com> a
écrit :

**Comment by alexmyczko** [comment]
looks it's not a public API :( https://github.com/hansemannn/iOS12-CarPlay-Example

**Comment by NexusEast** [comment]
any updates on support Apple CarPlay.?

**Comment by alexmyczko** [comment]
@NexusEast i wasn't able to use modizer on apple carplay with ios 14 beta 3, thus i'm limited to listening with myTuner Radio (there are like the best channels disco polo freszzzz and so on), https://www.youtube.com/watch?v=Oi1AL4pPczA

**Comment by yoyofr** [comment]
Hello, Carplay is now implemented in upcoming v3.1 (to be released very soon)
