### ISSUE TITLE
Downloads feature throws the towel too easily

### ISSUE THREAD

**Issue by sdsnatcher** [yoyofr/modizer#36]
The downloads feature only works fine on a stable WiFi connection. But it throws the towel too easily if anything gets rought. For example:

- When connected to more unstable networks like 3G or 4G: has issues to connect to FTP, gives up too easly, then resume doesn't work anymore
- When the lock screen is activated (clears the download list)

Many other events can make it clear the download list, forcing the user to search all over again and again for the modules he wanted to download.

**Comment by yoyofr** [comment]
v3.6 will improve download management: files list will be saved when leaving modizer and files shouldn't disappear from the list when they cannot be downloaded (unstable network for example).

**Comment by yoyofr** [comment]
v3.6 released
