### ISSUE TITLE
“∞” function issues

### ISSUE THREAD

**Issue by aitchFactor** [yoyofr/modizer#37]
When playing certain file formats, most prominently VGM/VGZ and anything supported by the vgmstream plugin, the ∞ function does not work as intended. 
Instead of looping the song continuously it will fade out the song after a period of time and restart from the beginning. The best workaround I can find for some of these file formats is to go into the plugin settings and set the “max loop” slider to the maximum level, although this will only loop the song 16 times instead of indefinitely.

**Comment by yoyofr** [comment]
Hi,


OK I will check. Could you give me some file names to test ?

**Comment by aitchFactor** [comment]
[03 Player Select.zip](https://github.com/yoyofr/modizer/files/3574007/03.Player.Select.zip)

[06 Invincible.zip](https://github.com/yoyofr/modizer/files/3574012/06.Invincible.zip)

**Comment by yoyofr** [comment]
fixed in upcoming v2.9.5
