### ISSUE TITLE
Bump AdPlug dependency to latest version

### ISSUE THREAD

**Issue by badja** [yoyofr/modizer#38]
The version of AdPlug used by Modizer is 2.2, which is over 8 years old. Support for several new formats has been added since then, as detailed in the [NEWS](https://github.com/adplug/adplug/blob/master/NEWS) file.

Note that in the latest version of AdPlug (currently 2.3.2) there are now two music formats that use the CMF file extension (_Creative Music File Format by Creative Technology_ and _SoundFX Macs Opera tracker by Linel_).

**Comment by yoyofr** [comment]
Hello,

I’m working on modizer v2.94, Adplug latest version is now integrated. I hope to be able to publish it in the coming weeks to the App Store.

Rgds,
ym

**Comment by apgrucza** [comment]
Hi, any progress on the new version (v2.94)?

**Comment by yoyofr** [comment]
hi, no progress since July, no time to work on it so far. I'm currently resuming work so it should happen soon, just need to check it compiles with latest xcode version / sdk.

**Comment by yoyofr** [comment]
fixed in v2.9.4
