### ISSUE TITLE
USF Tempo Issues

### ISSUE THREAD

**Issue by Tanookirby** [yoyofr/modizer#42]
Hey, I've noticed that certain game tunes from the Nintendo 64 play absurdly fast when played in your app. Examples of soundtracks include this Super Mario 64
[Rerip](
http://usf.joshw.info/s/Super%20Mario%2064%20(1996-06-23)(Nintendo%20EAD)(Nintendo)%5bN64%5d%5brerip%5d.7z).

**Comment by yoyofr** [comment]
fixed in upcoming v2.95
