### ISSUE TITLE
Support MPTM module format

### ISSUE THREAD

**Issue by LovelyA72** [yoyofr/modizer#43]
Currently mptm files are not listed in the file browser. Since Modizer is using libopenmpt, mptm support should work out of the box.

Thank you

**Comment by yoyofr** [comment]
Hello,

Thanks for raising this. I’m just in the middle of upgrading to v2.94. Just tested mptîm on a few files and yes it seems to work out of the box.
Will include it in next version.

Rgds,
Yoyofr

**Comment by yoyofr** [comment]
fixed in v2.9.4
