### ISSUE TITLE
Support for .hca Game Music Files

### ISSUE THREAD

**Issue by Tanookirby** [yoyofr/modizer#44]
I tried adding files with the .hca extension into Modizer, but they are not showing up. I've been converting most of my game music files to this format to save space, and I would appreciate it if this were supported.

More info on it https://fileinfo.com/extension/hca

**Comment by yoyofr** [comment]
Hello

I have a new version of modizer almost ready. I will check if I can quickly add hca support but not sure as it requires a recent vgmstream version, which means also dependencies to several additional external software libraries that currently not exist for iOS.

Rgds,
ym

**Comment by yoyofr** [comment]
Good news, I did a quick vgmstream update to latest version with only Ogg Vorbis & MPEG support and HCA seems to play fine (only did a quick test). I will include it in upcoming 2.94 version.

**Comment by Tanookirby** [comment]
OK, thanks. In the meantime, do you think you can tackle these issues?
https://github.com/yoyofr/modizer/issues/42
https://github.com/yoyofr/modizer/issues/37
