### ISSUE TITLE
VGMStream Issue

### ISSUE THREAD

**Issue by vus7294** [yoyofr/modizer#45]
I Tried to Play Those Format with New 2.9.4, It Not Working:
.at3
.at9
.xma
.xwb
.msf (Under Defeat HD PS3 MSF)
and Also VGMStream Looping Option Not Working as Well.(Song starts Less 1 Sec, and Force Repeat)
and Modizer UTF-8 Non-English Strings Seems not Working(all of strings crash)

**Comment by vus7294** [comment]
Additional Not Working File: .xwma(Dust an Elysian Tale), over 2 channel Sound File(Sound Completely Crashed)

**Comment by yoyofr** [comment]
Hi,

yes, some files are relying on codec not available in current modizer version. I'm planning to include ffmpeg in next version, it should allow better coverage

**Comment by yoyofr** [comment]
Working on a new build with ffmpeg included, will publish a v2.9.5 soon.
Tried several .at3 and .at9 that were not working in v2.9.4, now it is ok.
For xma, xwb, ..., please send me link/files to test

**Comment by vus7294** [comment]
[xma](http://x360.joshw.info/d/DoDonPachi%20Saidaioujou%20%282013-05-30%29%28Cave%29%5BX360%5D.7z), [xwb](http://x360.joshw.info/a/Akai%20Katana%20%5BAkai%20Katana%20Shin%5D%20%282011-05-26%29%28Cave%29%5BX360%5D.7z), [xwb loseless?](http://x360.joshw.info/d/DoDonPachi%20Daioujou%20Black%20Label%20Extra%20%282009-02-19%29%28Cave%29%285pb%29%5BX360%5D.7z), [http://psf3.joshw.info/u/Under%20Defeat%20HD%20%282012-02-23%29%28G.Rev%29%5BPS3%5D.7z](msf), [over 2channel](http://3sf.joshw.info/y/Yoshi%27s%20New%20Island%20%282014-03-14%29%28Arzest%29%28Nintendo%29%5B3DS%5D.7z)

**Comment by yoyofr** [comment]
Ok thanks, all are working with my new version, thanks to ffmpeg integration. I need to fix a few other issues and I’ll release v2.9.5.

**Comment by vus7294** [comment]
Also Vgmstream infinity Loop option has problem well.
If i turned on Loop option, Song plays less 1 second and force repeat same song. Can you find what is problem? Thanks a lot.

**Comment by yoyofr** [comment]
yes, I just fixed it as well. The loop management was totaly wrong.

**Comment by yoyofr** [comment]
fixed in upcoming v2.9.5
