### ISSUE TITLE
Another USF Tempo Issue

### ISSUE THREAD

**Issue by Tanookirby** [yoyofr/modizer#47]
First of all, many thanks for solving the infinity loop problem. Now I can insert many more soundtracks without any issues.

About my problem, I noticed certain USF sets are no longer being played at a crazy speed, but now I believe they are being played a bit too slowly. Track rerips like the ones for Super Mario 64 and Mario Kart 64 now play with the slower tempo much like their initial versions. They seem to work perfectly when played in Foobar with the USF Decoder component. So what's going on here?

**Comment by yoyofr** [comment]
ok thanks for the feedback.
I did a quick test and I'm not sure what you mean by modizer playing slightly slowly compared to foobar.
I'm using kode54 source code for lazyusf2 which is the same code used in foobar2000 for the USF decoder.
The only difference I noticed is that I was not taking into account the fade time at the end of the song. For example mario kart 64 select & setup music is 1:16 long in Foobar2000 (5s of fadeout time) compared to 1:11 in modizer.
Also the fadeout time is added to the main time in foobar2000 but there is no real fadeout (progressive decrease of volume) applied to the song. I might add proper fadeout management in modizer in next version.
Are you sure the song are played a little bit more slowly in Modizer ?
If so I would need a file to test and a reference to compare (youtube link would be perfect)

**Comment by Tanookirby** [comment]
It would be more like this: https://www.youtube.com/watch?v=da4-9blmg3Y&list=PL354A16B73ABB107D&index=19

**Comment by yoyofr** [comment]
ok thanks, I will check

**Comment by yoyofr** [comment]
ok, that's fixed. I did not use the latest lazyusf library version in v2.9.5. Using the latest one from kode54 it now sounds good. Will try to publish a v2.9.6 quickly, probably this weekend
