### ISSUE TITLE
Update plugins/libraries used

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#48]
As was mentioned in #42 about the USF issue (and because I saw libsidplayfp update to 2.1.1 yesterday or so), it might be a good idea to update the libraries used to mitigate any issues the current versions could have.

**Comment by yoyofr** [comment]
ok, I'll check. Updating librairies is not always straightforward so I'm not doing it systematically on each update.

**Comment by yoyofr** [comment]
Fixed in v2.9.6
