### ISSUE TITLE
VGMPlay player does not loop tracks

### ISSUE THREAD

**Issue by yoshisuga** [yoyofr/modizer#51]
This happened with the most recent version.

Repro steps:
- Play a vgm file like an .nsf - anything that shows the format "VGM" on the info screen
- Tap the infinity ∞ button to loop the track

Observed:
- VGM format files like nsf and many others played by the VGMPlay player does not loop the track and will fade out and start at the first track or replay it.

Expected:
VGM format files should loop endlessly like they did before.

I noticed that other players like the gameboy player, the loop works as expected.

I tried debugging the app after I got it to build but couldn't find where this problem is originating. I'll try to dig deeper.

**Comment by yoyofr** [comment]
OK thanks for the detailed and clear report.
I'm working on v2.96,  will fix it.

**Comment by yoyofr** [comment]
fixed, to be released in v2.9.6
