### ISSUE TITLE
Most SIDs creating a buzzing noise

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#52]
With the latest update, most SIDs are now playing back a buzzing noise, as if it were constantly restarting, with Mr_Marvellous.sid it restarts about 34 seconds after the song had begun playing, so this bug seems to affect every SID.

https://files.catbox.moe/0htycd.MP4

Edit: this only seems to occur with infinite playback enabled

**Comment by yoyofr** [comment]
Hi,

thanks for the report. It's a bug with the "infinite" play mode. I will fix
it asap. Meanwhile please do not use the "infinite" play mode with SID (do
not activate the  horizontal 8 button)

**Comment by 0x5066** [comment]
Thank you for responding immediately! 👍

**Comment by yoyofr** [comment]
welcome, currently uploading v2.961 with the required fix, should be available by tomorrow on the app store if nothing goes wrong
