### ISSUE TITLE
Option for fadeout times

### ISSUE THREAD

**Issue by Tanookirby** [yoyofr/modizer#53]
For vgmstream-supported files, I strongly suggest having an option to choose the fadeout time because whenever I have the infinite loop disabled, every song just abruptly stops at the end.

**Comment by yoyofr** [comment]
OK I will check.

Le jeu. 25 mars 2021 à 20:02, Tanookirby ***@***.***> a
écrit :

**Comment by yoyofr** [comment]
I did an option for fadeout time in current dev version, will be included in next release. But with current vgmstream library logic, it seems to be only applied to streams that have loop points defined, i.e. if it is just a stream file without loop defined, no fadeout is applied.
