### ISSUE TITLE
GSF Infinity Loop option Still not Work.

### ISSUE THREAD

**Issue by vus7294** [yoyofr/modizer#57]
It has long time since GSF Support, but GSF infinity loop option still lacks. And only 2 loop guaranteed.
Is GSF plugin has issue or bug for that? Thanks.

**Comment by yoyofr** [comment]
Hi, actually I fixed this issue a few days ago. I'm in the middle of a more global update, preparing for modizer v3.0.
GSF infinite loop mode bugfix will be part of it.
