### ISSUE TITLE
OpenMPT resampler

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#58]
The OpenMPT resampler option won't apply on first play, i.e. I selected to use "Near" though when restarting the app, it will play in Linear mode instead of what I wanted, to fix this one has to restart the song

**Comment by yoyofr** [comment]
Hi,
Yes, that was a limit in previous version and not sure it has changed. Changing the resampler in the middle of playback was not possible. I will check if it is still the case

Rads,
Ym

**Comment by yoyofr** [comment]
fix added in the current dev version. will be part of v3.0
