### ISSUE TITLE
reSID causes ear piercing output instead of actual playback

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#62]

**Comment by yoyofr** [comment]
To confirm: you selected "ReSID" isntead of "ReSIDFP" in the plugins/SID settings screen, right ?
Could you also give some examples (files names) ?
I did some tests with ReSID and have no pb on the files I tried. To confirm your settings tab for plugins/SID would be useful

**Comment by yoyofr** [comment]
ok, I found one using the files you provided for the other issue you raised.
I think that's a limit of ReSID, that's one the dev team is now pushing for ReSIDFP
Please stick with ReSIDFP, ReSID is for old devices and not as good as ReSIDFP

**Comment by 0x5066** [comment]
Found another SID that produces an ear piercing sound, \MUSICIANS\J\Jammer\Mr_Marvellous.sid

**Comment by yoyofr** [comment]
It's a limit with ReSID, no way to fix it, use ReSIDFP instead.
