### ISSUE TITLE
Oscilloscope with SIDs that have digis stretches out to a very long duration instead of what it should be

### ISSUE THREAD

**Issue by 0x5066** [yoyofr/modizer#63]
Example of such songs are:
MUSICIANS\J\Jammer\Jogging_Naked.sid
MUSICIANS\M\Mahoney\Monophono.sid
MUSICIANS\M\Mahoney\Musik_Run_Stop.sid

**Comment by yoyofr** [comment]
hi, I did some tests and I think it will be very difficult to implement oscilloscope/voices for this kind of file.
They use some very advanced c64 sid coding to play samples.
The best is to use standard stereo oscilloscope for this files, I will implement an option iin v3.1
