### ISSUE TITLE
I suggest adding a channel name prompt to the oscilloscope screen

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#64]
Currently, neither the oscilloscope screen nor the channel solo interface displays the specific name of the channel.

**Comment by denjhang** [comment]
For example: YM2608
FM 01~FM 06
Rhythm 01~06
SSG 1~3
ADPCM

**Comment by yoyofr** [comment]
hello,

yes I'm planning to progressively implement this (as an option)

Le sam. 24 avr. 2021 à 18:40, Denjhang Liu ***@***.***> a
écrit :

**Comment by yoyofr** [comment]
implemented in v3.4
