### ISSUE TITLE
Music display piano keyboard in vgm format

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#65]
Just like MDPlayer
https://github.com/kuma4649/MDPlayer
![截图未命名210321230738](https://user-images.githubusercontent.com/61811583/115966235-3edbcb00-a55f-11eb-93bb-6d3e6567457f.jpeg)

**Comment by yoyofr** [comment]
hi,
yes, I had also this in mind as a new FX/visualizer option

Le sam. 24 avr. 2021 à 18:43, Denjhang Liu ***@***.***> a
écrit :

**Comment by yoyofr** [comment]
v3.6 will feature something similar, here's a preview based on my current dev build (running on macos).
I've modified libvgm to add a note grabber in all default emulation core. Probably not 100% accurate but it looks already good 
<img width="971" alt="Capture d’écran 2024-04-27 à 20 33 23 1" src="https://github.com/yoyofr/modizer/assets/1301623/71d812b8-a670-42fd-880a-c21819001927">

**Comment by yoyofr** [comment]
v3.6 released
