### ISSUE TITLE
Playing music in SNSF format, switching tracks causes a crash.

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#67]
With one tap, the app disappears and returns to the desktop

**Comment by yoyofr** [comment]
hello, please give some examples / files. the snsf I tried are working well

Le sam. 24 avr. 2021 à 18:55, Denjhang Liu ***@***.***> a
écrit :

**Comment by yoyofr** [comment]
fixed in current dev version. Will be included in v3.1

**Comment by denjhang** [comment]
On iphone11, as long as it is playing snsf, no matter which package it is, it can only play the first one, and it will flash back as soon as the track is switched.

**Comment by yoyofr** [comment]
yes. Did you see my previous comment ? I just fixed this bug in the dev version. It will be included in v3.1.
