### ISSUE TITLE
Whether it can support FMP, PMD and other formats.

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#69]
I need support for the following formats:
PC98:FMP,S98
Sharp X68000:NRD
MSX:MDR,MGS,MPK,MFM,MBM,MWM,MUS,OPX,PRO,SBM,SNG
ZX-128+:AMAD,
midi format variants:RMF,MMF
Of course, I prefer to support YAMAHA SMAF (.mmf) format, which may be a bit difficult.

**Comment by yoyofr** [comment]
ok I will check, some should already be supported. Could you please be more specific and give some files examples.

**Comment by yoyofr** [comment]
some are already supported, did you try (see below) ?
Could you please only raise requests for what is missing or if you have bugs/issues, thanks.
MDX player: MDX, PDX
SC68 player: SC68
OMPT/XMP players: AMF
GME player:AY
Adplug player: D00/DRO/IMF/RAD/RAW/SOP

**Comment by denjhang** [comment]
Since the FMP source code is not open, I suggest you refer to this project.https://github.com/takamichih/fmplayer
The project includes the reverse cracked FMP player core.
The source code of PMD is open, and the format is implemented in Droidsound-E.

**Comment by denjhang** [comment]
The following compressed package contains typical FMP music files.
[FMP Demo.zip](https://github.com/yoyofr/modizer/files/6372171/FMP.Demo.zip)

**Comment by denjhang** [comment]
The following compressed package contains typical PMD music files.
[Uploading PMD.zip…]()

**Comment by denjhang** [comment]
This is the PMD source code
https://sites.google.com/site/kajapon/pmd

**Comment by denjhang** [comment]
http://nrtdrv.sakura.ne.jp/
This is the website in NRD format (NRTDRV)

**Comment by denjhang** [comment]
https://github.com/BouKiCHi/moondrv
This is the website in MDR format (Moondriver)

**Comment by denjhang** [comment]
MPK
http://xray.delta-z.org/mpk.html

**Comment by denjhang** [comment]
http://sakuramail.net/fswold/music.html
MGS,OPX,MPK,SCC-music

**Comment by yoyofr** [comment]
ok thanks. Are you also reading my replies/comments ? PMD is already implemented in Modizer since quite long 🙂

**Comment by denjhang** [comment]
The S98 format does not seem to be supported.

**Comment by yoyofr** [comment]
I confirm, it’s not supported for now

**Comment by yoyofr** [comment]
S98 and Fmp are now supported. No plan for the other formats.
