### ISSUE TITLE
sidplay click noise when starting a new tune

### ISSUE THREAD

**Issue by yoyofr** [yoyofr/modizer#71]

**Comment by 0x5066** [comment]
I wouldn't say it's really a bug, as popping is unavoidable even in songs, particularly with the 6581 (the 8580 has quieter popping but it's still there)

**Comment by yoyofr** [comment]
Yes, I agree. I did some checks as I'm not a C64 specialist and I understand it's normal behaviour of the SID chips.
so closing this one.
