### ISSUE TITLE
The oscilloscope of the OPL rhythm drum channel is displayed separately.

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#72]
At present, the rhythm drum sound channel of OPLL is not displayed at all. OPL, OPL2, OPL3, OPL4's rhythm drum  channel are displayed on the 7/8/9 channel,And mixed together.

**Comment by denjhang** [comment]
And the rhythm drum channel can't be muted, even if I choose to mute the 7/8/9 channel.

**Comment by yoyofr** [comment]
Hi,

Yes I’m aware, it’s how the OPLL emulator is working right now. I need to check if I can change the code to isolate rhythm channels

**Comment by yoyofr** [comment]
Yes, it’s a bug that will be fixed in next version.
