### ISSUE TITLE
Crash on first run

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#73]
On iPhone XS, when the phone is turned on and the modizer is run for the first time and the compressed package is opened, the software will crash, but not when the software is run for the second time.

**Comment by denjhang** [comment]
This problem has always existed and is very annoying.

**Comment by yoyofr** [comment]
I will need more details: what are you doing exactly ? Are you launching modizer, then selecting a file (which file, in which screen) ?
Or are you selecting a file out of modizer, for example in the ‘file’ application or in Safari (browser) ?

**Comment by yoyofr** [comment]
To fix it I need more info as I don’t have the problem when I use modizer myself.
Please describe step by step with details so I can fix it

**Comment by denjhang** [comment]
After the iPhone XS phone is turned off and turned on (actually, the modizer is not running in the background, the process is completely killed), click the modizer icon on the desktop, open the application, and click Downloads. The modizer immediately returns to the desktop without any pop-up prompts. Click the modizer icon on the desktop again, after opening the application, and clicking Downloads, no exception occurred.

**Comment by yoyofr** [comment]
Ok thanks, but difficult to guess what generates the crash. I have fixed several bugs, let’s check if you still have the issue in upcoming v3.1

**Comment by denjhang** [comment]
At present, I found that iPhone11 also has this problem.
For example, when I haven't used Modizer for a day or two, after opening Modizer again and clicking Downloads, the software will crash immediately.
Or when I use Modizer to listen to music, a phone call comes in suddenly. When I end the call and enter Modizer again, click Downloads, and the software will crash immediately.

**Comment by yoyofr** [comment]
I'm not able to reproduce the issue but I have fixed several issues in my current dev build.
v3.1 will be available in a few days.
If you still have the issue in v3.1 open a new bug report with the details of your downloads folder. If it continues to crash it might be related to language (I assume you're using Chinese as primary language) or file names in your downloads folder.
