### ISSUE TITLE
When there is a mixture of multiple format music files in the compressed package, the program crashes

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#77]
This problem often arises.

**Comment by yoyofr** [comment]
As usual, without more details I cannot fix anything.
I need more details, which combination of files inside a compressed package generate the issue ?

**Comment by denjhang** [comment]
[DSE-Examples.zip](https://github.com/yoyofr/modizer/files/6526927/DSE-Examples.zip)
This is actually a sample track of DroidSound-E.

**Comment by denjhang** [comment]
[PC-98 Touhou Music.zip](https://github.com/yoyofr/modizer/files/6526947/PC-98.Touhou.Music.zip)

**Comment by yoyofr** [comment]
Please retry in v3.1 when it will be available as I don't have issue on my side.
