### ISSUE TITLE
Using the SID music played back by sampling, the oscilloscope displays an error

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#81]
Using the SID music played back by sampling, the oscilloscope displays an error, and the channel cannot be closed

**Comment by denjhang** [comment]
[Great_Giana_Sisters.zip](https://github.com/yoyofr/modizer/files/6528329/Great_Giana_Sisters.zip)

**Comment by denjhang** [comment]
![BAFE23273EA6ED27D703285BC7760A92](https://user-images.githubusercontent.com/61811583/119266458-849eb880-bc1d-11eb-90bf-00cda10d1d4f.png)

**Comment by yoyofr** [comment]
the voice control issue is fixed in upcoming v3.1.
For the oscilloscope, it is not an error, it is what is generated by the SID chipset.
"Sample based" sid musics are using special hardware tricks that prevent oscilloscope view to work.
