### ISSUE TITLE
Randomizer only plays first file in .zip/.7z when playing multiple

### ISSUE THREAD

**Issue by rayjkayj** [yoyofr/modizer#84]
I’ve noticed that when using the random play function with multiple .zip/.7z that it only plays the first file within them. Doesn’t matter which format they contain. Is this sonething that can get fixed? 

Also just want to say that I’ve been using Modizer since it was released and am so greatful that you have been updating it steadily these past 10 years. Keep up the awesome work!

**Comment by yoyofr** [comment]
ok thanks for the report, I just fixed this bug. Will be part of v3.1
