### ISSUE TITLE
When playing SID music, the length of multiple sub-tracks is too short

### ISSUE THREAD

**Issue by denjhang** [yoyofr/modizer#85]
When I played robocop3.sid, I found that the first track was only played about half the length, so I switched to the next track automatically.

**Comment by denjhang** [comment]
[RoboCop_3.zip](https://github.com/yoyofr/modizer/files/6539542/RoboCop_3.zip)

**Comment by yoyofr** [comment]
Probably an old Sid version.
If you use the file from hvsc, length will be correct.
(Song length are based on STIL library, relying on md5 checksum of the Sid file)
