### ISSUE TITLE
Compressed archive files play only the first song

### ISSUE THREAD

**Issue by Tanookirby** [yoyofr/modizer#88]
Whenever I chose a file inside an archived set such as 7z, it plays only the first song. When shuffle is on, it will go to a random song.

**Comment by rayjkayj** [comment]
It’s working, Just set player to random and hit play all on a folder containing Zip files and it played tracks other than the first one in the archive. Thanks!

On Jun 9, 2021, at 3:37 PM, Tanookirby ***@***.***> wrote:

﻿

Whenever I chose a file inside an archived set such as 7z, it plays only the first song. When shuffle is on, it will go to a random song.

**Comment by yoyofr** [comment]
Thanks for the feedback 👍

**Comment by yoyofr** [comment]
I confirm, there's a regression in v3.1. Will publish a patch asap

**Comment by miker84** [comment]
Question, does this not occur if the archive is uncompressed?

**Comment by miker84** [comment]
Hi @yoyofr,  any update on when the match might be released?

**Comment by yoyofr** [comment]
Hi,

I hope before end of the month.

Rgds,
Ym

**Comment by miker84** [comment]
Hello @yoyofr ,  how are things?  No worries if you've been busy.  Just checking in to see if there have been any updates on progress of the update.

**Comment by andrebreves** [comment]
Any updates on this issue? I'm also unable to select a song to play when browsing a .zip file, only the first song plays (or a random one when shuffle is active) regardless the song I click.

**Comment by yoyofr** [comment]
will be part of v3.2 that will be released very soon
