### ISSUE TITLE
Change Global Playback Tempo / Play Speed & Transposition

### ISSUE THREAD

**Issue by jlturner** [yoyofr/modizer#92]
Hey there, love your project, thanks for your work! Been using it daily for almost 10 years and just donated, totally worth it!

Feature requests:

- I've been extensively using your recent feature of toggling voice channels, and I would love to see a global tempo / play speed to slow down / speed up songs as well.

- Additionally being able to transpose either all voices or individual voices would be pretty great!

**Comment by yoyofr** [comment]
Thanks for the feedback and sorry for the late reply.
I could check if a slowdown/speedup feature could be implemented, similar to what YouTube provides for example.
But not sure if users will be interested.
What would be your usage / objective ?

**Comment by yoyofr** [comment]
v3.6 released with new settings to manage playback ratio for vgm & gme files

**Comment by jlturner** [comment]
Wow thank you so much, I meant to respond earlier but it fell by the wayside. Just sent a donation through your website / PayPal. Like I said I have use it almost daily for almost 10 years, gotta support the band!

To answer your original question, a lot of VGM and Chiptunes are pretty fast paced, and I love listening to them when working over long sessions. It's really nice dropping some instruments and slowing it down (I do this on OpenMPT when I can). Sometimes speeding up a bit is nice too!

Love your global tempo implementation, only suggestion would be more granularity to the slider (maybe a step size of 5% / 0.05) and alter the slider max range to 300% (3.0).

Thanks again!

**Comment by jlturner** [comment]
Wow, so quick to implement that! You are the best! Thank you so much!
