### ISSUE TITLE
No DMA channel playback (SNDH)

### ISSUE THREAD

**Issue by gitGalu** [yoyofr/modizer#97]
DMA playback is disabled in SNDH player. I haven't found any settings for this particular player/format so it's probably a bug.

Please compare:
MODLAND/DMA-SC/SNDH/travellers.sndh
https://www.youtube.com/watch?v=eujNEb_Qoa8

MODLAND/DMA-SC/SNDH/ymetal.sndh
https://soundcloud.com/dma-sc/ymetal

**Comment by yoyofr** [comment]
yes, there are issues with DMA in sc68 playback lib. I tried psgplay which is newer and seems to be updated but there's the same limit in current version.
If you're aware of a better playback library I can try to integrate it in modizer.

**Comment by yoyofr** [comment]
v3.3 will use a new player for sndh, atarisound which should fix the DMA channel issue
